name: deploy-to-cloudflare
on:
  push:
    branches: [ main ]

display-name: "部署到Cloudflare Pages"

stages:
  - name: build-and-deploy
    display-name: "构建并部署"
    fail-fast: true
    
    steps:
    - name: checkout
      uses: git-checkout
      
    - name: setup-node
      uses: node-setup
      with:
        version: 18
        
    - name: install-dependencies
      run: npm install
      
    - name: install-wrangler
      run: npm install -g wrangler
      
    - name: deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        echo "开始部署到Cloudflare Pages..."
        wrangler pages deploy public --project-name=hours-guard --commit-message="Auto deploy"