name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Wrangler CLI
      run: npm install -g wrangler
      
    - name: Deploy to Cloudflare Pages
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        echo "🚀 Starting deployment to Cloudflare Pages..."
        echo "Project: hours-guard"
        echo "Commit: ${{ github.sha }}"
        wrangler pages deploy public --project-name=hours-guard --commit-message="Auto-deploy from Gitee: $(date +%Y-%m-%d_%H:%M:%S)"