name: 部署到Cloudflare Pages

on:
  push:
    branches: [ main ]

display-name: "自动部署"

stages:
  - name: 部署
    steps:
    - name: 检出代码
      uses: git-checkout
      
    - name: 安装Node.js
      uses: node-setup
      with:
        version: '18'
        
    - name: 安装依赖
      run: npm install
      
    - name: 安装Wrangler
      run: npm install -g wrangler
      
    - name: 部署
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        echo "开始部署..."
        wrangler pages deploy public --project-name=hours-guard --commit-message="Auto deploy"